---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: disable-automount-default-sa-controller
  name: disable-automount-default-sa-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: disable-automount-default-sa-controller-sa-cr
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "patch", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: disable-automount-default-sa-controller-sa
  namespace: disable-automount-default-sa-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: disable-automount-default-sa-controller-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: disable-automount-default-sa-controller-sa-cr
subjects:
  - kind: ServiceAccount
    name: disable-automount-default-sa-controller-sa
    namespace: disable-automount-default-sa-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: disable-automount-default-sa-controller-lease-cr
  namespace: disable-automount-default-sa-controller
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "patch", "update", "delete","create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: disable-automount-default-sa-controller-rb
  namespace: disable-automount-default-sa-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: disable-automount-default-sa-controller-lease-cr
subjects:
  - kind: ServiceAccount
    name: disable-automount-default-sa-controller-sa
    namespace: disable-automount-default-sa-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: disable-automount-default-sa-controller
  namespace: disable-automount-default-sa-controller
  labels:
    app: disable-automount-default-sa-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: controller
          image: disable-automount-default-sa-controller:1.0.0
          imagePullPolicy: Never # this forces k8s to use local image that we loaded via kind
          env:
            - name: CONTROLLER_NAMESPACE
              value: disable-automount-default-sa-controller
          resources:
            requests:
              memory: 512Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 400m
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false 
      serviceAccountName: disable-automount-default-sa-controller-sa
